### ISSUE TITLE
library questions

### ISSUE THREAD

**Issue by sdmcallister** [bung87/scorper#11]
Impressive work! 

Just wondering if you think that scorper is ready for production (ie. could be used in place of jester in terms of api stability, performance, and features).  I'm strongly considering it for an upcoming project but it is also fairly new.  

Maybe eventually submit to the techempower benchmarks? 

Thank you.

**Comment by bung87** [comment]
there's metal problem am not really sure
1. exceptions handle:  https://github.com/bung87/scorper/issues/2 and https://github.com/status-im/nim-chronos#exception-effects  
2. my multipartparser implementation write by myself not sure if there's problem https://github.com/bung87/scorper/blob/devel/src/scorper/http/multipartparser.nim  
3. form data same key https://github.com/bung87/scorper/issues/8  this api definitely will change.  

I checked  techempower recently , it including mysql testing , so I add chronos support to my [amysql](https://github.com/bung87/amysql) these days, about performance it bit faster than go's `fasthttp`.  

am very concern about the program stability, performance seems fine to me.

**Comment by bung87** [comment]
addition: "Parse JSON streamingly." this have not be done, since other apis all streamingly, I dont wanna loss this part.

**Comment by bung87** [comment]
@sdmcallister Thanks for interested in my project! Please give a try v1.0.5, fix some metal problems. others parts I consider as features.

**Comment by sdmcallister** [comment]
Thank you for the active development.
