### ISSUE TITLE
Error: can raise an unlisted exception: Exception

### ISSUE THREAD

**Issue by sdmcallister** [bung87/scorper#27]
Can't compile with flag `-d:chronosStrictException`

Example:
`nim r -d:chronosStrictException scorpertest.nim`
Error:
`scorper-1.0.15\scorper\http\streamserver.nim(355, 24) Error: can raise an unlisted exception: Exception`

**Comment by bung87** [comment]
oh , this flag is like strict mode, so without this flag , the program should also work , it's usage kind like a linter. so dont worry about this.

**Comment by bung87** [comment]
close in 1.0.16
