### ISSUE TITLE
get cookie value

### ISSUE THREAD

**Issue by sdmcallister** [bung87/scorper#33]
Is there a proc that returns the value of a cookie? Something like:
```
proc getCookie(req: Request, val: string): string =
  let 
    c = req.headers.table.getOrDefault("Cookie", @[""])
    cookies = c[0].parseCookies()
  result = cookies.getOrDefault(val)
```
I did a search but didn't see a proc for this. I used the std lib for the `parseCookies` proc.

**Comment by bung87** [comment]
yeah, haven't implement such a api , I think you can do `let c:string = req.headers["Cookie"]; let cookies = c.parseCookies()`,  `import std/cookies` first.

**Comment by bung87** [comment]
fixed in https://github.com/bung87/scorper/commit/25316365c7f70ee782d6a9b61ade07fba503eac7 v1.0.18
