### ISSUE TITLE
Request - Parse JSON string to Object directly

### ISSUE THREAD

**Issue by shayanhabibi** [bung87/scorper#37]
[I've used jsony](https://github.com/shayanhabibi/scorper/commit/9708c6efe021cbc9b7f31760d55b1d8453e116ae#diff-73ac9bef3015e0c1d751cc86ca77df910721a1bc1082c4ab9a74a9afecb9bd69R574) to directly parse the string to an object since treeform mentions that the stringstreams are actually slower for this use anyway; is this indeed an efficient method?

Sorry my commit diff is horrible due to my editor settings, the link goes directly to the proc I added to your source code.

Else see here:

```nim
# scorper/src/scorper/http/streamserver.nim

proc obj*[T](req: ImpRequest, x: typedesc[T]): Future[T] {.async.} =
  if req.rawBody.isSome:
    return req.rawBody.unSafeGet.fromJson(T)
  var str: string
  result = "{}".fromJson(T)
  try:
    str = await req.reader.readLine(limit = req.contentLength.int)
  except AsyncStreamIncompleteError as e:
    await req.respStatus(Http400, ContentLengthMismatch)
    result = "{}".fromJson(T)
    req.rawBody = some(str)
    req.parsed = true
    return result
  try:
    result = str.fromJson(T)
  except CatchableError as e:
    raise newHttpError(Http400, e.msg)
  except Exception as e:
    raise newHttpError(Http400, e.msg)
  req.rawBody = some(str)
  req.parsed = true
```

**Comment by bung87** [comment]
here are some thoughts.
`jsony` is loose so it does not validate the input json string is valid or not, you may get corrupt json data.
Here I don't use `stringstreams` I wish I find a lib that accept parse from network io buffer.
Am not sure provide a api "Parse JSON string to Object directly" , is it necessary ? End developer can convert from JsonNode by calling one proc.

**Comment by shayanhabibi** [comment]
I suppose depends on needs; I am using this as my Scorper will be deployed in an internal environment where I need rapid serialisation and deserialisation. The conversion of string to JsonNodes before converting then to Objects is a sacrifice I can't make in this enterprise. Because I am assured the json is valid since I am developing the client ui which is interacting with the scorper it is a very useful api for myself. Perhaps offering it as an unsafe api?

I will require it in my own project however will keep it in my own fork for the future.

**Comment by bung87** [comment]
I think we can expose an API wraps exists json api , handle json parse logic in same place. the main concerns here is I want response error automatically when json data is not valid.

**Comment by bung87** [comment]
well , If you still need implement your own json handler , I think you can use scorper `.stream` api which returns a stream reader, you can use it in your own json handler or obj handler.
