### ISSUE TITLE
Multiline body with windows CRLF carriage is not correct processing by scorper

### ISSUE THREAD

**Issue by alexisad** [bung87/scorper#40]
Processed only first line of body.

It also causes crash of scorper if is sending request using Postman from Windows (send please request for 2 or more times) because lines separated by CRLF (\r\n)
This was sent by Postman:
```
curl --location --request POST 'http://127.0.0.1:8888/jobs/run' \
--header 'Connection: keep-alive' \
--header 'Content-Type: text/plain' \
--data-raw '1 test
2 test
3 test'
```

Scorper server:
```nim
import scorper

proc createJob*(req: Request) {.route(["post"], "/jobs/run"), async.} =
    echo "headers:", req.headers
    let body = await req.body()
    echo "body was red, len:", body.len
    let headers = {"Content-type": "text/plain"}
    await req.resp("OK", headers.newHttpHeaders())



let address = "127.0.0.1:8888"
let flags = {ReuseAddr}
let router = newRouter[ScorperCallback]()
router.addRoute(createJob)

let server = newScorper(address, router, flags)
server.start()
waitFor server.join()

```

Crash output:
Scorper serve at http://127.0.0.1:8888
headers:{"User-Agent": @["PostmanRuntime/7.29.0"], "Content-Length": @["22"], "Host": @["127.0.0.1:8888"], "Accept": @["*/*"], "Connection": @["keep-alive"], "Content-Type": @["text/plain"]}
body was red, len:6
127.0.0.1:8888 - - 2022-03-20T16:54:15+01:00 "POST /jobs/run HTTP/1.1" 200 OK 2
/home/alex/nimapps/here_batch_geo/multbody.nim(20) multbody
/home/alex/.nimble/pkgs/chronos-3.0.11/chronos/asyncloop.nim(1091) waitFor
/home/alex/.nimble/pkgs/chronos-3.0.11/chronos/asyncloop.nim(279) poll
/home/alex/.nimble/pkgs/scorper-1.0.26/scorper/http/streamserver.nim(702) processRequest
/home/alex/.choosenim/toolchains/nim-1.6.4/lib/system/assertions.nim(38) failedAssertImpl
/home/alex/.choosenim/toolchains/nim-1.6.4/lib/system/assertions.nim(28) raiseAssert
/home/alex/.choosenim/toolchains/nim-1.6.4/lib/system/fatal.nim(53) sysFatal
[[reraised from:
/home/alex/nimapps/here_batch_geo/multbody.nim(20) multbody
/home/alex/.nimble/pkgs/chronos-3.0.11/chronos/asyncloop.nim(1091) waitFor
/home/alex/.nimble/pkgs/chronos-3.0.11/chronos/asyncloop.nim(279) poll
]]
Error: unhandled exception: /home/alex/.nimble/pkgs/scorper-1.0.26/scorper/http/streamserver.nim(702, 10) `headerEnd != -1`  [AssertionDefect]

**Comment by bung87** [comment]
could you create a PR for this? I am a mac user, rarely use windows

**Comment by bung87** [comment]
also add a unit test file under tests directory, CI including windows platform, so once your PR ready it can runs agianst that

**Comment by alexisad** [comment]
Thanks.

if i understand correct, is needed to fix in streamserver.nim in proc body:

instead of `result = await req.reader.readLine(limit = req.contentLength.int)`
this:
```nim
let resSeqBytes = await req.reader.read()
result = newString(resSeqBytes.len)
copyMem(result[0].addr, resSeqBytes[0].unsafeAddr, resSeqBytes.len)

```

I tried it but is hanging up forever on the line `let resSeqBytes = await req.reader.read()`

**Comment by bung87** [comment]
I think you should go to src/scorper/http/mofuparser.nim 
the returned value `-1` is from there.
