### ISSUE TITLE
server crash under multiple browser refreshes (F5)

### ISSUE THREAD

**Issue by nimelias** [bung87/scorper#47]
```
/chronos/asyncfutures2.nim(586) cb
Error: unhandled exception: Asynchronous task [processClient() at streamserver.nim:811] finished with an exception "AsyncStreamWriteEOFError"!
Message: Stream finished or remote side dropped connection
```

The same happens when in a route handler there is something like `await sleepAsync(5000)` and refresh page is requested.

**Comment by bung87** [comment]
anything I need to know for reproducing this ?

I never had this issue, and I tried today.

**Comment by nimelias** [comment]
i cannot setup a static dir server. feel free to close the issue.
btw trying the error i get is: `scorper/src/scorper/http/streamserver.nim(105, 15) Error: undeclared field: 'path' for type urlly.Url:ObjectType`

**Comment by bung87** [comment]
it happens when you run with `nim c -r ` instead of `nimble c -r`, they may use different packages.
